### ISSUE TITLE
Config.AimbotConfig.Shots.Value disregarded in adaptive rcs

### ISSUE THREAD

**Issue by koassount** [sirk1x/ResurrectedEternal#3]
I'm not sure if this is intended or not but usually when you can configure "shots fired" in an RCS it means that the RCS will turn ON after x "shots" so that you can single tap or burst without getting annoyed by it. 
[Here it's seemingly the opposite (turn off after x "shots")](https://github.com/sirk1x/ResurrectedEternal/blob/d9bae2aaa8a46ca12786b5a752a0d2aed9119fb8/Skills/GamePlaySkillMods/SkillModAim.cs#L394)

[Also not sure if intended, but adaptive RCS doesn't use Config.AimbotConfig.Shots.Value at all.](https://github.com/sirk1x/ResurrectedEternal/blob/d9bae2aaa8a46ca12786b5a752a0d2aed9119fb8/Skills/GamePlaySkillMods/SkillModAim.cs#L385)

edit: the spread visualization doesn't work at all and I'm also guessing, based on that, that the spread check for snipers doesn't work either.

**Comment by sirk1x** [comment]
By spread visualization you mean the the [AccuracyPenalty](https://github.com/sirk1x/ResurrectedEternal/blob/d9bae2aaa8a46ca12786b5a752a0d2aed9119fb8/Skills/GamePlaySkillMods/AimExtension/AccuracyPenalty.cs) or the [weapon_debug_spread_show](https://github.com/sirk1x/ResurrectedEternal/blob/d9bae2aaa8a46ca12786b5a752a0d2aed9119fb8/Configs/GamePlayConfig/VisualConfig.cs#L228) convar? The convar is visual only and just "draws" the box around your normal crosshair. The AccuracyPenalty does perform very poorly and will need a couple of tweaks, but it somewhat works.

The **Adaptive smooth** option means that the recoil control will be applied "over time" by taking the [deltatick](https://github.com/sirk1x/ResurrectedEternal/blob/d9bae2aaa8a46ca12786b5a752a0d2aed9119fb8/Clockwork/Clock.cs#L28) from the Clock.cs component. As an example, the standard setting is "over 1 second apply 0.0222f until we reach 1f (* 2f) with each tick". If we're above 1 second we just want to return the full compensation.

The **Incremental smooth** option means that the recoil control will be applied over "how many shots have been fired".
We start at 1 and increment by curShots / maxShots (0.25f) until we reach 1f * rcsCompensation (2f). 
if we're above maxShots, we'll just return the full compensation.

The process is called Linear Interpolation between two values, Lerp.

Setting the option to **None** will turn the rcs on after x shots and it will behave like your standard rcs.
